server:
  port: 8090
management:
  health:
    elasticsearch:
      enabled: false
my:
  elasticsearch:
    uris: 127.0.0.1:9500,127.0.0.1:9600,127.0.0.1:9700
    username: elastic
    password: nbcb,123